export const ErrorCode = {
  // Bids
  PLACE_NOT_FOUND: "PLACE_NOT_FOUND",
  PLACE_NOT_AVAILABLE: "PLACE_NOT_AVAILABLE",
  BID_BLACKOUT_DATE: "BID_BLACKOUT_DATE",
  BID_TOO_LOW: "BID_TOO_LOW",
  BID_OVERLAP_PENDING: "BID_OVERLAP_PENDING",
  BID_NOT_FOUND: "BID_NOT_FOUND",
  BID_FORBIDDEN: "BID_FORBIDDEN",
  BID_NOT_PENDING: "BID_NOT_PENDING",
  BID_NOT_ACCEPTED: "BID_NOT_ACCEPTED",
  // Payments
  INVENTORY_SOLD_OUT: "INVENTORY_SOLD_OUT",
  PAYMENT_FORBIDDEN: "PAYMENT_FORBIDDEN",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_NO_INTENT: "PAYMENT_NO_INTENT",
  PAYMENT_ALREADY_AUTHORIZED: "PAYMENT_ALREADY_AUTHORIZED",
  PAYMENT_ALREADY_CAPTURED: "PAYMENT_ALREADY_CAPTURED",
  STRIPE_KEY_MISMATCH: "STRIPE_KEY_MISMATCH",
  STRIPE_TEST_CARD_NOT_ALLOWED: "STRIPE_TEST_CARD_NOT_ALLOWED",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
