/* eslint-disable max-lines */
/** Full legal text — hardcoded from client PDF. Do not parse at runtime. */
import {
  LegalH2,
  LegalH3,
  LegalNotice,
  LegalP,
  LegalUl,
  LegalMeta,
  LegalToc,
  LegalCopyright,
} from "./LegalTypography";

export function PrivacyPolicyContent() {
  return (
    <>
      <LegalMeta
        operator="Operated by Student Deadline Inc"
        effectiveDate="April 27, 2026"
        lastUpdated="April 27, 2026"
      />
      <LegalP key="intro-0">This Privacy Policy (the “Policy”) describes how Student Deadline Inc, a California limited liability company doing business as Death Is A Deadline (“Death Is A Deadline,” “we,” “us,” or “our”), processes personal information in relation to your use of the Service. The “Service” means our website at https://death-is-a-deadline-mvp.vercel.app/, any successor domain, any mobile applications we publish, and the related application programming interfaces, features, tools, and services we own, operate, or provide. Death Is A Deadline operates a verified-identity, blind-bidding marketplace for members of the academic community (current college and university students, faculty, and staff). Because we verify eligibility through .edu email confirmation and/or review of identification documents, this Policy explains how we handle that additional category of personal information in addition to the data we collect to operate a hotel-booking marketplace. This Policy applies to users of the Service. If you are an employee, contractor, applicant, or hotel partner, separate notices may apply to your relationship with us. If you reside in California, see Section 8 for state-specific rights under the California Consumer Privacy Act, as amended (“CCPA”). The Service is offered from and intended for users located in the United States; we do not currently offer the Service in the European Economic Area, the United Kingdom, or other jurisdictions outside the U.S. You must be at least 18 years old to create an account or use the Service. We do not knowingly collect personal information from children under 18.</LegalP>
      <LegalToc items={["1. What is Personal Information","2. Who Controls My Personal Information","3. Personal Information We Collect","4. How We Use Personal Information We Collect","5. Sharing and Disclosure of Personal Information","6. Mobile Applications and Device Permissions","7. Third-Party Partners and Integrations","8. Your Rights and Choices","9. Retention","10. Security","11. Changes to This Privacy Policy","12. Contact Information","13. Definitions"]} />

      <LegalH2 key="b-0">1. What Is Personal Information</LegalH2>
      <LegalP key="b-1">“Personal information” refers to any information that is related to, associated with, or could reasonably be linked to an identified or identifiable individual. Some categories of personal information are treated as sensitive under applicable law (for example, government-issued identification numbers, precise geolocation, and account credentials); we identify these where they appear in this Policy and apply additional protections.</LegalP>
      <LegalH2 key="b-2">2. Who Controls My Personal Information</LegalH2>
      <LegalP key="b-3">Where this Policy mentions “Death Is A Deadline,” “we,” “us,” or “our,” it refers to Student Deadline Inc, a California limited liability company doing business as Death Is A Deadline, which is the entity responsible for your personal information under this Policy (the “Controller”). Our contact details are in Section 12. Death Is A Deadline acts solely as a technology marketplace connecting users with independent Hotels and does not itself provide accommodations or travel services. Hotels are independent controllers of personal information once a Reservation is formed. Hotels you transact with through the Service are independent businesses and are separate controllers of any personal information you provide directly to them or that we share with them once your Bid is accepted. Their handling of that personal information is governed by their own privacy practices, not by this Policy.</LegalP>
      <LegalH2 key="b-4">3. Personal Information We Collect</LegalH2>
      <LegalP key="b-5">We may obtain the following categories of personal information, depending on how you interact with the Service.</LegalP>
      <LegalH3 key="b-6">3.1 Personal Information Needed to Use the Service</LegalH3>
      <LegalP key="b-7">We collect personal information when you register, place a Bid, or otherwise use the Service. Without it, we may not be able to provide all features. This includes:</LegalP>
      <LegalH3 key="b-8">3.1.1 Contact, Account, and Profile Information.</LegalH3>
      <LegalP key="b-9">Information you provide when you set up an account or use the Service, such as your first and last name, phone number, email address, and account password (stored in hashed form by our authentication provider).</LegalP>
      <LegalH3 key="b-10">3.1.2 Academic Verification Information (Eligibility Data).</LegalH3>
      <LegalP key="b-11">Because the Service is restricted to current students, faculty, and staff, we collect information necessary to verify your eligibility, including:</LegalP>
      <LegalUl key="b-12" items={["Your .edu (or equivalent recognized academic) email address and the result of the one-time verification email we send to it;","If you choose manual review or your domain is not eligible for automatic verification: an image of a current student, faculty, or staff identification document (front and, where applicable, back), which may include your name, photograph, institution name, and an institution-issued ID number; and","The institution name, role (student, faculty, or staff), and verification status we record on your account, along with the date and method of verification. We treat ID-document images and any government-issued or institution-issued ID numbers contained in them as sensitive personal information. We use them solely for eligibility verification, fraud prevention, and compliance, retain them only as long as needed for those purposes (see Section 9), and do not sell them or use them for advertising."]} />
      <LegalH3 key="b-13">3.1.3 Bid and Reservation Information.</LegalH3>
      <LegalP key="b-14">Information generated when you submit a Bid or hold a Reservation, including the Hotel(s) and date(s) you selected, your bid amount, the outcome of the bid (accepted or rejected), the timestamp, the device used, the resulting reservation details (confirmation number, check-in/check-out dates, room type if assigned), and any modifications, cancellations, or no-show flags reported by the Hotel.</LegalP>
      <LegalH3 key="b-15">3.1.4 Payment Transaction Information.</LegalH3>
      <LegalP key="b-16">Payment-related information necessary to process accepted Bids. All card data is collected and processed by Stripe, Inc. (“Stripe”), our PCI-compliant payment processor. Death Is A Deadline does not store your full card number or CVV. We receive from Stripe a payment-method token, the brand and last four digits of your card, the billing zip code, the charge amount and currency, and authorization, capture, refund, and dispute outcomes. Your use of Stripe is also subject to Stripe’s own privacy notice. Payment processing services are provided by Stripe and are subject to Stripe’s terms and privacy practices. Death Is A Deadline is not responsible for the security or processing of payment information handled by Stripe.</LegalP>
      <LegalH3 key="b-17">3.2 Personal Information You Choose to Give Us</LegalH3>
      <LegalP key="b-18">You may choose to provide additional information, including:</LegalP>
      <LegalH3 key="b-19">3.2.1 Information About Others.</LegalH3>
      <LegalP key="b-20">Personal information about another guest in your traveling party (such as a name associated with the reservation), or about a person on whose behalf you are authorized to bid. By providing personal information about others, you certify that you have authority to do so for the purposes described in this Policy and that you have shared this Policy with them.</LegalP>
      <LegalH3 key="b-21">3.2.2 Support Information.</LegalH3>
      <LegalP key="b-22">Messages, attachments, and (where applicable and consistent with applicable law) call recordings or transcripts collected when you contact our support team to investigate and respond to your concerns and to monitor and improve our support processes.</LegalP>
      <LegalH3 key="b-23">3.2.3 Reviews and Ratings.</LegalH3>
      <LegalP key="b-24">Review content, ratings, and any photos you choose to submit about a Hotel stay booked through the Service.</LegalP>
      <LegalH3 key="b-25">3.2.4 Other Information.</LegalH3>
      <LegalP key="b-26">Information you choose to share when you respond to surveys, participate in research, refer a friend, apply for an ambassador or campus-rep role, enter promotions, or otherwise share your experience with us. We will collect any personal information you voluntarily provide, including any sensitive personal information you choose to disclose.</LegalP>
      <LegalH3 key="b-27">3.3 Information Automatically Collected by Using the Service</LegalH3>
      <LegalH3 key="b-28">3.3.1 Geolocation Information.</LegalH3>
      <LegalP key="b-29">Approximate location derived from your IP address, and (only with your permission) more precise location from your mobile device’s GPS or browser geolocation, used to show you nearby Hotels and to set reasonable defaults for your search. You can control or revoke location permissions in your device or browser settings at any time. Precise geolocation is treated as sensitive personal information.</LegalP>
      <LegalH3 key="b-30">3.3.2 Usage Information.</LegalH3>
      <LegalP key="b-31">Information about how you interact with the Service, including the Hotels and dates you search, Bid and reservation history, pages and screens viewed, links clicked, session timestamps, and the referring/exit pages. We may collect this information from users who have not created an account or logged in.</LegalP>
      <LegalH3 key="b-32">3.3.3 Device Information.</LegalH3>
      <LegalP key="b-33">IP address, access dates and times, hardware and software characteristics, browser and operating system version, language, time zone, mobile network information, device identifiers, and crash data. We may collect this information from users who have not created an account or logged in.</LegalP>
      <LegalH3 key="b-34">3.3.4 Cookies and Similar Technologies.</LegalH3>
      <LegalP key="b-35">We and our service providers use cookies, pixels, SDKs, local storage, and similar technologies to authenticate you, remember your preferences, secure the Service, measure performance, and (where you opt in) personalize marketing. You can control cookies through your browser settings and through the in-product cookie controls we provide where required by law. We may use advertising and remarketing technologies, including tools such as Meta Pixel, Google Ads, or similar services, to measure the effectiveness of our campaigns and deliver relevant advertisements. These tools may collect information about your interactions with the Service and other websites. Some browsers offer a “Do Not Track” feature. Our Service does not currently respond to Do Not Track signals.</LegalP>
      <LegalH3 key="b-36">3.4 Personal Information We Collect from Third Parties</LegalH3>
      <LegalP key="b-37">We may use third-party identity or student verification providers to confirm eligibility.</LegalP>
      <LegalH3 key="b-38">3.4.1 Authentication Providers.</LegalH3>
      <LegalP key="b-39">If you sign in with a third-party identity provider (for example, Google or another single-sign-on we may enable), you direct that provider to send us limited profile information (such as your name, email address, and a unique account identifier) as controlled by that service or as authorized by you in its privacy settings.</LegalP>
      <LegalH3 key="b-40">3.4.2 Verification, Anti-Fraud, and Hosting Vendors.</LegalH3>
      <LegalP key="b-41">We may receive signals from identity-verification, anti-fraud, hosting, and infrastructure providers (for example, hosting and analytics from Vercel; payment risk signals from Stripe; deliverability signals from our email provider; and any manual-review service we use for ID documents) that help us confirm eligibility, detect fraud, and keep the Service available.</LegalP>
      <LegalH3 key="b-42">3.4.3 Hotels and Co-Travelers.</LegalH3>
      <LegalP key="b-43">If a person adds you to a reservation as a co-guest, that person may submit limited information about you (such as your name and email address). Hotels may also report back to us the status of your reservation, including check-in, no-show, charges incurred at the property, or incident reports.</LegalP>
      <LegalH3 key="b-44">3.4.4 Other Sources.</LegalH3>
      <LegalP key="b-45">To the extent permitted by applicable law, we may receive additional information about you and your activities from publicly available sources, our partners, and fraud-prevention or risk-assessment services, and combine it with information we already hold for the purposes described in Section 4.</LegalP>
      <LegalH2 key="b-46">4. How We Use Personal Information We Collect</LegalH2>
      <LegalP key="b-47">We use personal information for the purposes described below. Where applicable U.S. state law requires it, we limit our use of sensitive personal information (such as ID-document images and precise geolocation) to the purposes permitted by that law.</LegalP>
      <LegalH3 key="b-48">4.1 Provide the Service. We process personal information to:</LegalH3>
      <LegalP key="b-49">lCreate, secure, and maintain your account, including authenticating logins; lVerify that you are an eligible member of the academic community via the methods described in Section 3.1.2;</LegalP>
      <LegalUl key="b-50" items={["Display Hotel options based on your search criteria and (with permission) your approximate location;","Receive, evaluate, and process your Bids against each Hotel’s confidential Floor Base, charge accepted Bids through Stripe, and transmit confirmed Reservations to the Hotel;","Provide receipts, reservation confirmations, modifications, and check-in details;","Provide customer support and respond to your requests; and","Send transactional and account messages, security alerts, and required notices."]} />
      <LegalH3 key="b-51">4.2 Improve and Develop the Service.</LegalH3>
      <LegalUl key="b-52" items={["Perform analytics, debugging, and research;","Improve and develop the Service, including the design of the bidding flow, matching logic, and search ranking; and","Train customer-support staff and improve our quality assurance."]} />
      <LegalH3 key="b-53">4.3 Personalize and Customize the Service.</LegalH3>
      <LegalUl key="b-54" items={["Personalize your experience based on prior searches, Bid and reservation history, stated preferences, and other information you choose to give us; and","Tailor content within the Service, such as suggested destinations, dates, or Hotel types."]} />
      <LegalH3 key="b-55">4.4 Safeguard the Service and Community.</LegalH3>
      <LegalP key="b-56">lDetect, assess, address, and prevent fraud, identity misrepresentation, abuse, spam, security incidents, and other harmful activity; lVerify or authenticate eligibility, payment, and account information, including by checking ID documents and email-domain signals against our records and reasonable third-party data sources; lConduct security investigations and risk assessments; lEnforce these Terms, our other policies, and our agreements with Hotels and vendors; lComply with our legal obligations and respond to lawful requests from courts, law enforcement, regulators, or tax authorities; and lWhere appropriate, restrict, suspend, or terminate access to the Service when our automated or human review detects activity that poses a safety, fraud, or other risk. If you would like to challenge a decision based on automated processes, please contact us as described in Section 12. lWe may use and retain personal information, including transaction and device data, to investigate and respond to payment disputes, chargebacks, and suspected fraud, and may share such information with payment processors and financial institutions as necessary.</LegalP>
      <LegalH3 key="b-57">4.5 Provide, Personalize, Measure, and Improve Our Marketing.</LegalH3>
      <LegalUl key="b-58" items={["Send promotional, marketing, and advertising messages via email, SMS (where you have consented), or push notification, subject to your opt-in or opt-out choices;","Personalize, measure, and improve our marketing campaigns, including campus, ambassador, and referral programs;","Administer rewards, surveys, sweepstakes, contests, and other promotional activities; and","Analyze characteristics and preferences to send you content we believe may be of interest, including via cookies and similar technologies subject to your choices."]} />
      <LegalH2 key="b-59">5. Sharing and Disclosure of Personal Information</LegalH2>
      <LegalH3 key="b-60">5.1 With Your Consent or at Your Direction.</LegalH3>
      <LegalP key="b-61">Where you provide consent or direct us to share your personal information, we share it as described at the time of consent or choice — for example, when you authorize a third-party service to access your Death Is A Deadline account, publish a Review, or participate in a partner promotion.</LegalP>
      <LegalH3 key="b-62">5.2 Who We Share With.</LegalH3>
      <LegalH3 key="b-63">5.2.1 Hotels for Accepted Reservations.</LegalH3>
      <LegalP key="b-64">When your Bid is accepted, we share with the Hotel the personal information needed to honor the Reservation — typically your first and last name, email address, phone number, dates of stay, number of guests, any co-traveler names you provided, the confirmation number, and any special requests you submitted. We do not share your bid amount, the Hotel’s Floor Base, or the contents of your ID-verification documents with the Hotel. We do not verify the accuracy of information provided by Hotels and are not responsible for errors, omissions, or inaccuracies in information supplied by Hotels.</LegalP>
      <LegalH3 key="b-65">5.2.2 Co-Travelers.</LegalH3>
      <LegalP key="b-66">If you add another guest to a Reservation, your first and last name, travel dates, Hotel information, and other reservation details may be shared with that guest in the booking confirmation.</LegalP>
      <LegalH3 key="b-67">5.2.3 Vendors and Service Providers.</LegalH3>
      <LegalP key="b-68">
        We share personal information with service providers under contractual obligations that limit their use of that information to performing services for us. These currently include, without limitation:
      </LegalP>
      <LegalUl
        key="b-69"
        items={[
          "Hosting and infrastructure (e.g., Vercel) for serving the Application and associated logs;",
          "Payments (Stripe, Inc.) for processing card transactions, fraud signals, and dispute handling;",
          "Authentication and account security for sign-in, multi-factor authentication, session management, and abuse detection;",
          "Email and SMS delivery for transactional communications and, subject to your choices, marketing;",
          "Analytics and product telemetry to measure performance and improve the Service;",
          "Identity verification and manual ID review to confirm academic eligibility and detect fraud;",
          "Customer support tools for responding to your inquiries; and",
          "Professional advisors (lawyers, accountants, auditors, and insurers) where reasonably necessary.",
        ]}
      />
      <LegalH3 key="b-70">5.3 Why We May Share Your Personal Information.</LegalH3>
      <LegalH3 key="b-71">5.3.1 Comply with Law, Respond to Legal Requests, Prevent Harm, and Protect Our Rights.</LegalH3>
      <LegalP key="b-72">As we reasonably deem appropriate, we may disclose your personal information to courts, law enforcement, governmental or public authorities, tax authorities, and authorized third parties, if and to the extent we are required or permitted to do so by law and where disclosure is reasonably necessary to: (i) comply with our legal obligations; (ii) comply with a valid legal request such as a subpoena or court order; (iii) respond to claims asserted against Death Is A Deadline; (iv) address alleged or suspected illegal activity, including fraud, identity misrepresentation, or abuse; (v) enforce our agreements; (vi) respond to emergencies that may involve the risk of death or serious physical harm; or (vii) protect the rights, property, or personal safety of Death Is A Deadline, our users, our Hotels, our vendors, our affiliates, or members of the public. Where appropriate and not legally prohibited, we may notify you about legal requests.</LegalP>
      <LegalH3 key="b-73">5.3.2 Effectuate Business Transfers.</LegalH3>
      <LegalP key="b-74">If Death Is A Deadline undertakes or is involved in any merger, acquisition, reorganization, financing, sale of assets, bankruptcy, or insolvency event, we may share, transfer, or sell some or all of our assets, including personal information, in connection with such transaction or its negotiation. We will provide notice of any such transfer where required by law and before your personal information becomes subject to a different privacy policy.</LegalP>
      <LegalH3 key="b-75">5.3.3 Enable and Contextualize Reviews.</LegalH3>
      <LegalP key="b-76">If you choose to publish a Review, the Review content (including any photos) and limited associated information — such as your first name, last initial, the date you joined Death Is A Deadline, and the city or institution you are associated with — may be made publicly visible alongside your Review.</LegalP>
      <LegalH3 key="b-77">5.4 No Sale of Personal Information.</LegalH3>
      <LegalP key="b-78">We do not sell your personal information for money, and we do not use or share your ID-verification documents, bid history, or precise geolocation for cross-context behavioral advertising. Some of our analytics and marketing cookies may constitute “sharing” under California law; you can opt out of those uses as described in Section 8.</LegalP>
      <LegalH2 key="b-79">6. Mobile Applications and Device Permissions</LegalH2>
      <LegalP key="b-80">If we publish a mobile application, we may request device permissions for location, notifications, camera (for example, to capture an image of an ID document for verification), and contacts. These permissions are optional in most cases and you can grant, deny, or revoke them in your device settings at any time. You may uninstall the app at any time to discontinue collection of personal information by the app, and you may delete your account from within the app or by emailing us. If you have an active Reservation, we may not be able to delete your account until the Reservation is complete and any related dispute periods have closed.</LegalP>
      <LegalH2 key="b-81">7. Third-Party Partners and Integrations</LegalH2>
      <LegalP key="b-82">Parts of the Service may link to or integrate with third-party services that we do not own or control. When you interact with these third parties and choose to use their service, you are providing personal information to them, and your use is subject to their own terms and privacy practices. Examples include Stripe, Vercel, Google Maps and the Google Maps Additional Terms of Service, the Apple App Store and Google Play Store (if and when we publish a mobile application), and the Hotels you transact with.</LegalP>
      <LegalH2 key="b-83">8. Your Rights and Choices</LegalH2>
      <LegalP key="b-84">You can review and update much of your account information through your in-product settings, including updating your contact information, changing your password, managing notification preferences, and deleting your account. If you signed in with a third-party identity provider, you can unlink that provider through its own settings.</LegalP>
      <LegalH3 key="b-85">8.1 Communications Choices.</LegalH3>
      <LegalP key="b-86">You can opt out of marketing emails by using the unsubscribe link in any marketing email or by emailing us at the address in Section 12. You can opt out of marketing SMS by replying STOP to any marketing text from us. We may continue to send you transactional and account-related communications (for example, Bid acceptance notices, receipts, security alerts, and required legal notices) regardless of your marketing choices.</LegalP>
      <LegalH3 key="b-87">8.2 California Residents (CCPA/CPRA).</LegalH3>
      <LegalP key="b-88">If you are a California resident, you have the following rights under the California Consumer Privacy Act, as amended by the California Privacy Rights Act (collectively, the “ CCPA”), subject to applicable exceptions:</LegalP>
      <LegalUl key="b-89" items={["Right to know what categories and specific pieces of personal information we have collected about you, the sources, the purposes, and the categories of third parties to which we disclose it;","Right to delete personal information we have collected from you;","Right to correct inaccurate personal information we maintain about you;","Right to opt out of the “sale” or “sharing” of personal information for cross-context behavioral advertising. We do not sell personal information for money; to the extent any of our analytics or marketing cookies constitute “sharing,” you can opt out via the in-product cookie controls or by enabling a Global Privacy Control (GPC) signal in a supported browser;","Right to limit the use and disclosure of sensitive personal information to those uses permitted by the CCPA. As noted in Section 3.1.2, we already limit our use of ID-verification documents and other sensitive personal information to eligibility, fraud prevention, security, compliance, and delivery of the Service; we do not use them for inferring characteristics or for advertising; and","Right to non-discrimination for exercising any of these rights. To exercise these rights, contact us at the address in Section 12 with the subject “Privacy Request — California.” We will need to verify your identity using information already associated with your account before fulfilling a request. You may use an authorized agent to submit a request on your behalf, subject to verification of the agent’s authority. We will respond within the time periods required by law."]} />
      <LegalH3 key="b-90">8.3 Other U.S. State Residents.</LegalH3>
      <LegalP key="b-91">Residents of other U.S. states with comprehensive consumer privacy laws may have rights similar to those described above. Contact us as described in Section 12 to exercise any such rights, and we will respond as required by applicable law.</LegalP>
      <LegalH3 key="b-92">8.4 Cookie Controls.</LegalH3>
      <LegalP key="b-93">You can manage cookies through your browser settings and through any in-product cookie banner or preference center we provide. Disabling some cookies may impact the functionality of the Service.</LegalP>
      <LegalH2 key="b-94">9. Retention</LegalH2>
      <LegalH3 key="b-95">9.1 Retention Periods.</LegalH3>
      <LegalP key="b-96">We retain personal information for as long as needed for the purposes described in this Policy and as permitted by applicable law. The criteria we use to determine retention include:</LegalP>
      <LegalUl key="b-97" items={["Whether we have an ongoing relationship with you and provide the Service to you, and the period thereafter during which we may have a legitimate need to retain your information (for example, to manage and protect our business, address issues, or defend claims);","Whether we are subject to a legal, tax, accounting, reporting, or auditing obligation that requires us to keep records of your transactions for a defined period (for example, financial records of accepted Bids); and","Whether retention is advisable in light of our legal position, statutes of limitations, ongoing litigation, or regulatory investigations. Eligibility documents. Where we collect an image of an ID document for manual verification, we delete the image after a verification decision is recorded and any related fraud or appeal window has closed, unless a longer retention is required by law or necessary to investigate suspected fraud. We retain the verification result (for example, the institution name, role, and decision date), but not the image itself, for the life of your account and a reasonable period thereafter. Bid and payment records. We retain Bid history, accepted reservation details, and Stripe transaction records for the period required by tax, payment-card-network, and consumer-protection rules, generally not less than seven (7) years from the date of the transaction."]} />
      <LegalH3 key="b-98">9.2 Shared Information.</LegalH3>
      <LegalP key="b-99">Information you have shared with others using the Service, such as Reviews, may remain publicly visible after your account is deleted, unless you ask us to remove it and we are not otherwise required to retain it.</LegalP>
      <LegalH3 key="b-100">9.3 Residual Copies.</LegalH3>
      <LegalP key="b-101">Because we take measures to protect data from accidental or malicious use, loss, destruction, or alteration, residual copies of your personal information may not be immediately removed from our backup systems. We will continue to protect such residual copies in accordance with this Policy and delete them in the ordinary course of our backup-rotation schedule.</LegalP>
      <LegalH2 key="b-102">10. Security</LegalH2>
      <LegalP key="b-103">While no organization can guarantee perfect security, we implement and regularly update administrative, technical, and physical safeguards designed to protect personal information from unauthorized access, use, loss, destruction, or alteration. These measures include encryption in transit (HTTPS/TLS), encryption at rest for databases that store personal information, role-based access controls, logging and monitoring, secret management, vendor due diligence, and the use of PCI-compliant processors (Stripe) for card data. You are responsible for safeguarding your account credentials and should notify us immediately if you believe your account has been compromised.</LegalP>
      <LegalH2 key="b-104">11. Changes to This Privacy Policy</LegalH2>
      <LegalP key="b-105">We reserve the right to modify this Policy at any time in accordance with applicable law. If we do so, we will post the revised Policy on the Service and update the “Last Updated” date at the top. If the change is material, we will provide additional notice (for example, by email or in-app notification) before it takes effect. If you disagree with the revised Policy, you may close your account. If you do not close your account before the revised Policy becomes effective, your continued access to or use of the Service will be subject to the revised Policy.</LegalP>
      <LegalH2 key="b-106">12. Contact Information</LegalH2>
      <LegalP key="b-107">For questions or complaints about this Policy or about how Death Is A Deadline handles personal information, including to exercise any privacy rights, please contact us at: Student Deadline Inc d/b/a Death Is A Deadline Attn: Privacy Email: stay@thepodshare.com Site: https://death-is-a-deadline-mvp.vercel.app/</LegalP>
      <LegalH2 key="b-108">13. Definitions</LegalH2>
      <LegalP key="b-109">Capitalized terms not defined in this Policy have the meanings given in the Death Is A Deadline Terms of Service (the “Terms”). For convenience:</LegalP>
      <LegalUl key="b-110" items={["“Bid” — a binding offer you submit through the Service to pay a specified price for a reservation at a specified Hotel and date(s).","“Floor Base” — the confidential minimum acceptable rate set by a Hotel for a specific room and date.","“Hotel” — a hotel, resort, hostel, bed & breakfast, or similar accommodation provider listed on the"]} />
      <LegalH3 key="b-111">Service.</LegalH3>
      <LegalUl key="b-112" items={["“Reservation” — a confirmed booking created when a Hotel accepts your Bid.","“Service” — the Death Is A Deadline website, any related mobile application, and the related features and tools we provide.","“Stripe” — Stripe, Inc., our payment processor. © 2026 Student Deadline Inc. All rights reserved. Death Is A Deadline, the Death Is A Deadline logo, and “Life is short. Travel now.” are trademarks of Student Deadline Inc."]} />
      <LegalCopyright text="© 2026 Student Deadline Inc. All rights reserved. Death Is A Deadline, the Death Is A Deadline logo, and “Life is short. Travel now.” are trademarks of Student Deadline Inc." />
    </>
  );
}
